### ISSUE TITLE
No reference to 8ef2ec4b383e3b518fbfc462eee8d9c9786c3a64

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/small#35]
Current master (2.8.0) is looking at commit 8ef2ec4b, but the branch with that commit has already been deleted.

**Comment by Totktonada** [comment]
(Quite similar to #20.)

Mergen added the corresponding tag: [gh-35-do-not-remove](https://github.com/tarantool/small/releases/tag/gh-35-do-not-remove). The problem looks resolved.
